VIDEO_TMP_FILE_LOCATION="data/temp/"

PATH_TO_OBJECT_DETECTION_CONFIG = "config/ml_config/yolov4x-mish.cfg"
PATH_TO_OBJECT_DETECTION_WEIGHTS = "config/ml_config/yolov4x-mish.weights"
OBJECT_DETECTION_X_LOWER_BOUND = 0.4
OBJECT_DETECTION_X_UPPER_BOUND = 0.6