name: pylint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout common repo
      uses: actions/checkout@v2
      with: 
        repository: Seneca-AI/common
        token: ${{ secrets.ADMIN_TOKEN_LUCA }}
        persist-credentials: true
    - name: Upload python proto definitions
      uses: actions/upload-artifact@v2
      with:
        name: proto-definitions-python
        path: proto_out/python/api/type/


  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Download python proto definitions
      uses: actions/download-artifact@v2
      with:
        name: proto-definitions-python
        path: api/type/
    - name: Analyze relevant code with pylint
      # These ignored errors will be caught by tests and compilation, there's no sense in paying attention to them here.
      run: |
        pylint ml --disable=fixme,no-member,import-error
        pylint main.py --disable=fixme,no-member,import-error
      