on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: lint python
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pylint
      run: |
        pip install pylint

    - name: Run pylint
      run: |
        pylint evaluate
        pylint tests
        pylint utils