name: pylint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analyze relevant code with pylint
      run: |
        pylint ml --disable=fixme